### ISSUE TITLE
statsd reports

### ISSUE THREAD

**Issue by VolVoz** [yola/yodeploy#212]
Do we still use it for collect statistics? 
https://github.com/yola/yodeploy/blob/master/yodeploy/deploy.py#L66

Because of that code we have an error during deploy from flask-app:
```
Exception on /deploy/domainservice [POST]
Traceback (most recent call last):
  File "/srv/yodeploy/versions/304/virtualenv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/yodeploy/versions/304/virtualenv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/yodeploy/versions/304/virtualenv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/yodeploy/versions/304/virtualenv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/yodeploy/versions/304/virtualenv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/yodeploy/versions/304/virtualenv/local/lib/python2.7/site-packages/flask_httpauth.py", line 61, in decorated
    return f(*args, **kwargs)
  File "/srv/yodeploy/versions/304/yodeploy/cmds/../../yodeploy/flask_app/views.py", line 28, in deploy_app
    current_app.config, user)
  File "/srv/yodeploy/versions/304/yodeploy/cmds/../../yodeploy/deploy.py", line 121, in deploy
    deploy_settings, user)
  File "/srv/yodeploy/versions/304/yodeploy/cmds/../../yodeploy/deploy.py", line 71, in report
    % (environment, hostname, app.replace('.', '_')), addr)
gaierror: [Errno -2] Name or service not known
```

I propose to remove it and upgrade to deploy version on all of servers

**Comment by VolVoz** [comment]
ping @yola/service-engineering

**Comment by RayeN** [comment]
ping @yola/operations-engineering

**Comment by ekoval** [comment]
We don't even have Graphite for a long time I believe. It's host in YoDeploy's config on `serv1/2` is old and does not exist anymore.
I think we just need to re-deploy up-to-date YoDeploy everywhere.

**Comment by fr33l** [comment]
yeap, we killed graphite in https://github.com/yola/production/issues/4213, and yes, it's in configuration json because `Yodeploy` wasn't re-deployed in a whilie now... 

> I propose to remove it and upgrade to deploy version on all of servers

:+1:  for that :)

**Comment by stefanor** [comment]
I'm betting the flask server simply wasn't restarted since removing the statsd config from it.

Probably a missing dependency in chef.

**Comment by stefanor** [comment]
I think we can close this?
